ALTER TABLE bucket_transactions DROP CONSTRAINT check_type;

ALTER TABLE bucket_transactions ADD CONSTRAINT check_type CHECK ( type IN ('ADDFUNDS', 'REMOVEFUNDS', 'UNDO_ADDFUNDS', 'UNDO_REMOVEFUNDS', 'TRANSFER_ADDFUNDS', 'TRANSFER_REMOVEFUNDS'));